server:
  applicationConnectors:
    - type: http
      port: 28080
  adminConnectors:
    - type: http
      port: 28081

jobQueue: example

scheduler:
  sqs:
    inboundQueueName: inbound
    endpoint: 'http://localhost:4576'
  dynamoDb:
    schedulesTableName: dynein_schedules
    queryLimit: 10
    endpoint: 'http://localhost:4569'
  workers:
    numberOfWorkers: 1
    recoverStuckJobsLookAheadMs: 60000
    threadPoolSize: 2
    partitionPolicy: STATIC
    staticPartitionList: [0]
  heartbeat:
    monitorInterval: 60000
    stallTolerance: 300000
  maxPartitions: 1
